apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingapp
  labels:
    app: pingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingapp
  template:
    metadata:
      labels:
        app: pingapp
    spec:
      containers:
        - name: pingapp
          image: nicopaez/pingapp:2.1.0 
          ports:
          - containerPort: 4567
          envFrom:
            - configMapRef:
                name: configmap1
          volumeMounts:
          - name: configmap2
            mountPath: "/mydata/"
          - name: secret1
            mountPath: "/mysecrets/"
      volumes:
        - name: configmap2
          configMap:
            name: configmap2
        - name: secret1
          secret:
            secretName: secret1