version: "3"

services:
  password1:
    image: nicopaez/password-api
    ports:
      - "3003:3000"
    expose:
      - "3000"

  password2:
    image: nicopaez/password-api
    ports:
      - "3002:3000"
    expose:
      - "3000"
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8083:80"
    depends_on:
      - password1
      - password2
    links:
      - password1
      - password2
